### ISSUE TITLE
slackchannel2pdf can't read private channels

### ISSUE THREAD

**Issue by davisgoodman** [ErikKalkoken/slackchannel2pdf#1]
When the running the command it can't find private channels and not all of public channels:

```
slackchannel2pdf --token xoxp-2189032276.................... --add-debug-info 173115-gp2_phase3_expansion_ps
slackchannel2pdf v1.1.2 by Erik Kalkoken

Fetching workspace info from Slack...
Fetching users for workspace...
Fetching channels for workspace...
Fetching usergroups for workspace...

Welcome Davis Goodman
Fetching user info for author...
Timezone is: America/New_York
Locale is: English (United States) [en_US]
Adding DEBUG info to PDF
Writing output to: .
Page orientation: Portrait
Page format: A4

(1/1) ERROR: Unknown channel '1xxxx-privatechannel_expansion_ps' on ......... Company
```

**Comment by andrewjaanuu** [comment]
encountered the same issue today

**Comment by maziman84** [comment]
do we have solution for private channels? I have the same issue that the script does not work on some channels public and private (not sure what is the difference)

**Comment by ErikKalkoken** [comment]
Sorry for the late reply. Since we have a similar use case and the same error message, this looks to be the same bug as #4. Since the main discussion is in the other issue, I will close this one.
