### ISSUE TITLE
latin1 coding should be latin-1

### ISSUE THREAD

**Issue by marksolaris** [ErikKalkoken/slackchannel2pdf#18]
https://github.com/ErikKalkoken/slackchannel2pdf/blob/master/fpdf_mod/fpdf.py#L1325

I re-wrote it to be 
buffer = self.buffer.encode('latin-1', "ignore")

**Comment by ErikKalkoken** [comment]
Should be fixed with 1.5.1. Would be awesome if you could check and conform if the fix worked for you.

**Comment by marksolaris** [comment]
I'd like to test it but we've now completed the move away from Slack so I don't have the content to test against any more. Thanks for integrating the update!
