### ISSUE TITLE
typeError Unexpected value for identifier

### ISSUE THREAD

**Issue by willDTF** [ErikKalkoken/slackchannel2pdf#20]
trying to export multiple channel, i have the resulting 
![image](https://user-images.githubusercontent.com/4272733/226594471-b1e7b3c4-be12-403c-92f5-81e4dd6a6fbf.png)
i installed the tool in python 3.8 using pip (as described in description) 

then used : 

slackchannel2pdf --token TOKEN channelname1 channelname2 channelname3 --d D:/slack

I'm on windows 11 pro
any idea what's wrong ? 
thanks

**Comment by ErikKalkoken** [comment]
Should be fixed with 1.5.1. Would be awesome if you could check and conform if the fix worked for you.
