### ISSUE TITLE
ModuleNotFoundError: No module named 'fpdf_mod'

### ISSUE THREAD

**Issue by arvryna** [ErikKalkoken/slackchannel2pdf#25]
Hey @ErikKalkoken,

Thanks for the wonderful tool you built for exporting slack,. Ran into a small issue when running the CLI.

Getting this error, even though fpdf_mod is already installed, don't have a lot of experience in python to debug and fix it, could you suggest how can i fix it and get the tool up and running. 

Or please point me to .exe file of latest version if available.

![image](https://github.com/ErikKalkoken/slackchannel2pdf/assets/4346153/0a30ebf7-8974-44dd-a87e-8a747df24600)

**Comment by ErikKalkoken** [comment]
Hey!

Thanks for reporting this bug. I should be fixed with 1.5.2. Would be awesome if you could check it out and let me know if the bug has been fixed for you.

Cheers,
Erik

**Comment by arvpo** [comment]
sure, will verify , thanks for the quick fix
